### ISSUE TITLE
Issue with regex and capture groups

### ISSUE THREAD

**Issue by nk9** [ismaelgv/rnr#42] opened 2024-07-13 13:33 UTC
I am not sure if I'm doing something wrong here, but I'm trying to do this:

```
Statement_022024_1234.pdf->Statement_20240220_5678.pdf
```

But this command isn't doing what I expect:

```
rnr "_(\d\d)(\d\d)(\d\d)_1234" "_20${3}${2}${1}_5678" Statement_*
```

Instead, the dry run tells me that the command will do this:

```
Statement_022024_1234.pdf->Statement_20_5678.pdf
```

Is this a bug in `rnr`? I've just downloaded it, rnr 0.4.2

**Comment by ismaelgv** [comment] 2024-07-13 19:24
I think that the problem is that you are using double quotes (`"`). In most shells, these strings will interpolate the environmental variables and other expansions (e.g. wildcard *).

Try to use literal string with single quotes (`'`).

**Comment by nk9** [comment] 2024-07-13 20:31
That's totally it, and I see that there's even a note in the README about it. 😊

What do you think about providing a warning in the output (at least for the dry run environment) when the user attempts to interpolate a variable that doesn't exist?

**Comment by ismaelgv** [comment] 2024-07-13 20:37
I'm glad that fixed your problem. 👍

However, I am not sure if is worth it to add complexity to the tool just to show these kind of warning. I may take a look and make a decision.

**Comment by nk9** [comment] 2024-07-13 21:07
Just thinking aloud here: it would actually still be possible to provide a useful warning if the EXPRESSION pattern contains a different number of capture groups than are inserted in the REPLACEMENT pattern.

**Comment by ismaelgv** [comment] 2024-07-13 21:22
Yeah, I was thinking in that but I have to analyze some corner cases that it may appear with that changes. 

For example, the number of capture groups must be extracted first to be analyzed. Also, the capture groups in the replacement may appear repeated several times. It would need to find exactly that appear one or more times. Not sure if it worth the effort for little benefit.

I will take a look when I find some free time to explore the problem.

I will close the issue since the original problem is solved. Do not hesitate to report any bugs you may find.

**Closed** 2024-07-13 21:24 UTC

**Comment by nk9** [comment] 2024-07-13 22:31
Alright, thanks for your time and for the excellent OSS tool!
